CREATE TABLE [School] (
	idSchool int NOT NULL PRIMARY KEY,
	name varchar(30) NOT NULL,
	address varchar(30) NOT NULL

)

CREATE TABLE [Person] (
	idPerson int NOT NULL PRIMARY KEY,
	name varchar(30) NOT NULL,
	lastName varchar(30),
	birthday date NOT NULL
 

)

CREATE TABLE [Student] (
	idStudent int NOT NULL PRIMARY KEY,
	idSchool int NOT NULL 

)

CREATE TABLE [Employee] (
	idEmployee int NOT NULL PRIMARY KEY,
	salary int
)

CREATE TABLE [Janitor] (
	idJanitor bigint NOT NULL PRIMARY KEY,
	workingArea varchar(50) NOT NULL
 
)

CREATE TABLE [Employer] (
	idEmployer int NOT NULL PRIMARY KEY,
	licenseNumber int,
 

)

CREATE TABLE [Work] (
	idEmployee int NOT NULL PRIMARY KEY,
	idSchool int NOT NULL PRIMARY KEY

)

CREATE TABLE [Subject] (
	idStudent int NOT NULL PRIMARY KEY,
	idSubject int NOT NULL PRIMARY KEY,
)



ALTER TABLE [Student] WITH CHECK ADD CONSTRAINT [Student_fk0] FOREIGN KEY ([idStudent]) REFERENCES [Person]([idPerson])
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [Student] CHECK CONSTRAINT [Student_fk0]

ALTER TABLE [Student] WITH CHECK ADD CONSTRAINT [Student_fk1] FOREIGN KEY ([idSchool]) REFERENCES [School]([idSchool])
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [Student] CHECK CONSTRAINT [Student_fk1]


ALTER TABLE [Employee] WITH CHECK ADD CONSTRAINT [Employee_fk0] FOREIGN KEY ([idEmployee]) REFERENCES [Person]([idPerson])
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [Employee] CHECK CONSTRAINT [Employee_fk0]


ALTER TABLE [Janitor] WITH CHECK ADD CONSTRAINT [Janitor_fk0] FOREIGN KEY ([idJanitor]) REFERENCES [Employee]([idEmployee])
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [Janitor] CHECK CONSTRAINT [Janitor_fk0]


ALTER TABLE [Employer] WITH CHECK ADD CONSTRAINT [Employer_fk0] FOREIGN KEY ([idEmployer]) REFERENCES [Employee]([idEmployee])
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [Employer] CHECK CONSTRAINT [Employer_fk0]


ALTER TABLE [Work] WITH CHECK ADD CONSTRAINT [Work_fk0] FOREIGN KEY ([idEmployee]) REFERENCES [Employee]([idEmployee])
ON UPDATE CASCADE

ALTER TABLE [Work] CHECK CONSTRAINT [Work_fk0]

ALTER TABLE [Work] WITH CHECK ADD CONSTRAINT [Work_fk1] FOREIGN KEY ([idSchool]) REFERENCES [School]([idSchool])
ON UPDATE CASCADE

ALTER TABLE [Work] CHECK CONSTRAINT [Work_fk1]


ALTER TABLE [Subject] WITH CHECK ADD CONSTRAINT [Subject_fk0] FOREIGN KEY ([idStudent]) REFERENCES [Student]([idStudent])
ON UPDATE CASCADE

ALTER TABLE [Subject] CHECK CONSTRAINT [Subject_fk0]


ALTER TABLE [Person] ADD CONSTRAINT ON DELETE CASCADE;

ALTER TABLE [School] ADD CONSTRAINT ON DELETE RESTRICT;

